name: 'ChangeLog JSON'
description: 'GitHub Action that uses the GitHub API an generates a JSON file with the changelog'
author: darko.krizic@prodyna.com
inputs:
  github-token:
    description: 'The GitHub Token to use for authentication'
    required: true
  repositories:
    description: 'The repositories to query for the changelog'
    required: true
  organization:
    description: 'The organization to query for the repositories'
    required: true
  output-file:
    description: 'The output file to write the changelog to'
    required: true
    default: 'CHANGELOG.json'
  expand-links:
    description: 'Expand the links in the changelog'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/prodyna/changelog-json:v1.2'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    REPOSITORIES: ${{ inputs.repositories }}
    ORGANIZATION: ${{ inputs.organization }}
    OUTPUT_FILE: ${{ inputs.output-file }}
    EXPAND_LINKS: ${{ inputs.expand-links }}
